### ISSUE TITLE
cannot execute 'npm install ag-grid-ng2' - Exit status 1

### ISSUE THREAD

**Issue by karlcassar** [ceolter/ag-grid-ng2#54]
I am trying to call 'npm install ag-grid-ng2' and it is failing constantly, with just 'Exit status 1'. Below is the last part of the error log found in `npm-debug.log`.  Any ideas?  `ag-grid` installs fine.

```
55406 verbose lifecycle ag-grid-ng2@6.0.4~postinstall: PATH: C:\Users\kaca\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\git-repo\ag-grid-ng2-example-b\node_modules\ag-grid-ng2\node_modules\.bin;C:\git-repo\ag-grid-ng2-example-b\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\kaca\AppData\Roaming\npm
55407 verbose lifecycle ag-grid-ng2@6.0.4~postinstall: CWD: C:\git-repo\ag-grid-ng2-example-b\node_modules\ag-grid-ng2
55408 silly lifecycle ag-grid-ng2@6.0.4~postinstall: Args: [ '/d /s /c', './node_modules/.bin/typings install' ]
55409 silly lifecycle ag-grid-ng2@6.0.4~postinstall: Returned: code: 1  signal: null
55410 info lifecycle ag-grid-ng2@6.0.4~postinstall: Failed to exec postinstall script
55411 verbose unlock done using C:\Users\kaca\AppData\Roaming\npm-cache\_locks\staging-0d304289d54609e1.lock for C:\git-repo\ag-grid-ng2-example-b\node_modules\.staging
55412 silly rollbackFailedOptional Starting
55413 silly rollbackFailedOptional Finishing
55414 silly runTopLevelLifecycles Finishing
55415 silly install printInstalled
55416 warn optional Skipping failed optional dependency /chokidar/fsevents:
55417 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
55418 warn @angular/compiler-cli@0.6.1 requires a peer of typescript@^2.0.2 but none was installed.
55419 warn @angular/tsc-wrapped@0.3.0 requires a peer of typescript@^2.0.2 but none was installed.
55420 warn tsickle@0.1.7 requires a peer of typescript@^2.0.0 || ^2.1.0-dev but none was installed.
55421 verbose stack Error: ag-grid-ng2@6.0.4 postinstall: `./node_modules/.bin/typings install`
55421 verbose stack Exit status 1
55421 verbose stack     at EventEmitter.<anonymous> (C:\Users\kaca\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
55421 verbose stack     at emitTwo (events.js:106:13)
55421 verbose stack     at EventEmitter.emit (events.js:191:7)
55421 verbose stack     at ChildProcess.<anonymous> (C:\Users\kaca\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
55421 verbose stack     at emitTwo (events.js:106:13)
55421 verbose stack     at ChildProcess.emit (events.js:191:7)
55421 verbose stack     at maybeClose (internal/child_process.js:877:16)
55421 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
55422 verbose pkgid ag-grid-ng2@6.0.4
55423 verbose cwd C:\git-repo\ag-grid-ng2-example-b
55424 error Windows_NT 6.1.7601
55425 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaca\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
55426 error node v6.5.0
55427 error npm  v3.10.7
55428 error code ELIFECYCLE
55429 error ag-grid-ng2@6.0.4 postinstall: `./node_modules/.bin/typings install`
55429 error Exit status 1
55430 error Failed at the ag-grid-ng2@6.0.4 postinstall script './node_modules/.bin/typings install'.
55430 error Make sure you have the latest version of node.js and npm installed.
55430 error If you do, this is most likely a problem with the ag-grid-ng2 package,
55430 error not with npm itself.
55430 error Tell the author that this fails on your system:
55430 error     ./node_modules/.bin/typings install
55430 error You can get information on how to open an issue for this project with:
55430 error     npm bugs ag-grid-ng2
55430 error Or if that isn't available, you can get their info via:
55430 error     npm owner ls ag-grid-ng2
55430 error There is likely additional logging output above.
55431 verbose exit [ 1, true ]

```

**Comment by seanlandsman** [comment]
Looks like an issue with the post install for some reason.

What happens if you run just: ./node_modules/.bin/typings install ?

**Comment by seanlandsman** [comment]
Could be typescript 2 related - are you using typecript 2?

**Comment by seanlandsman** [comment]
Nevermind, I found the problem - for now please add 

"typings": "1.3.2" to your devDependencies

We'll shortly be upgrading to typescript 2 which will remove this issue. I'll revert on this thread when the issue has been resovled

**Comment by karlcassar** [comment]
Hi,

I already had ""typings": "1.3.2"  added to my devDependencies, and it is
installed. The issue  still persists.

Regards,
​Karl

**Comment by seanlandsman** [comment]
If typings was installed (via devDependencies) I'd expect ./node_modules/.bin/typings to be present too

What happens if you use run npm install typings ?

**Comment by karlcassar** [comment]
It seems to have installed successfully. There is one UNMET PEER DEPENDENCY
- not sure what that means.

$ npm install typings
ag-grid-ng2-example@6.0.2 C:\git-repo\ag-grid-ng2-example-b
+-- UNMET PEER DEPENDENCY typescript@1.8.10
`-- typings@1.4.0
  +-- typings-core@1.5.0
  | +-- configstore@2.1.0
  | | `-- os-tmpdir@1.0.2
  | `-- detect-indent@4.0.0
  |   `-- repeating@2.0.1
  |     `-- is-finite@1.0.2
  `-- update-notifier@1.0.2
    `-- xdg-basedir@2.0.0
      `-- os-homedir@1.0.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture:
fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.1 requires a peer of typescript@^2.0.2
but none was installed.
npm WARN @angular/tsc-wrapped@0.3.0 requires a peer of typescript@^2.0.2
but none was installed.
npm WARN tsickle@0.1.7 requires a peer of typescript@^2.0.0 || ^2.1.0-dev
but none was installed.


Regards,
Karl

**Comment by seanlandsman** [comment]
Ok, so with typings installed are you able to install ag-grid-ng2 now ?

Its worth noting that we'll be doing a release on monday that will make all of this moot - it wont be necessary to have typings anymore from monday onwards

**Comment by seanlandsman** [comment]
release of 6.1.0 removes typings - you should be able to install now
