### ISSUE TITLE
AOT build of ag-grid-ng2-example 'errors encountered resolving symbol values statically'

### ISSUE THREAD

**Issue by vwout** [ceolter/ag-grid-ng2#84]
While debugging an integration issue using ag-grid in an angular2 project using AOT, I decided to try the [example](https://github.com/seanlandsman/ag-grid-ng2-example) first. The error I get (both with ag-grid-ng2 6.4.2 using AgGridModule.withAotSupport() and 7.0.0-beta.* with AgGridModule.withComponents([])) is:
`Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /ag-grid-ng2-example/app/app.module.ts, resolving symbol AppModule in /ag-grid-ng2-example/app/app.module.ts`

I tried both node 6 and latest node 7.2.

Steps to reproduce (I use Docker to create a blank environment):

    $ git clone https://github.com/seanlandsman/ag-grid-ng2-example.git
    $ cd ag-grid-ng2-example/
    $ npm install
    ...
    npm info ok

    $ npm run build:aot
    npm info it worked if it ends with ok
    npm info using npm@3.10.9
    npm info using node@v7.2.0
    npm info lifecycle ag-grid-ng2-example@7.0.0-beta.2~prebuild:aot: ag-grid-ng2-example@7.0.0-beta.2
    npm info lifecycle ag-grid-ng2-example@7.0.0-beta.2~build:aot: ag-grid-ng2-example@7.0.0-beta.2

    > ag-grid-ng2-example@7.0.0-beta.2 build:aot /ag-grid-ng2-example
    > ngc -p tsconfig-aot.json && gulp aot-bundle

    Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /ag-grid-ng2-example/app/app.module.ts, resolving symbol AppModule in /ag-grid-ng2-example/app/app.module.ts
    at simplifyInContext (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:17938:25)
    at StaticReflector.simplify (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:17941:24)
    at StaticReflector.annotations (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:17428:38)
    at NgModuleResolver.resolve (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:11890:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:12275:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:12265:23)
    at addNgModule (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:17275:43)
    at /ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:17286:16
    at Array.forEach (native)
    at _createNgModules (/ag-grid-ng2-example/node_modules/@angular/compiler/bundles/compiler.umd.js:17285:28)
    Compilation failed

    npm info lifecycle ag-grid-ng2-example@7.0.0-beta.2~build:aot: Failed to exec build:aot script
    npm ERR! Linux 3.13.0-98-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:aot"
    npm ERR! node v7.2.0
    npm ERR! npm  v3.10.9
    npm ERR! code ELIFECYCLE
    npm ERR! ag-grid-ng2-example@7.0.0-beta.2 build:aot: `ngc -p tsconfig-aot.json && gulp aot-bundle`
    npm ERR! Exit status 1

**Comment by vwout** [comment]
At first site it looks like the problem was caused by angular 2.2.2 that was released 2016-11-22 22:45:07; that explains the build started to fail all of a sudden. The successor 2.2.3 was released one day later at 2016-11-23 23:13:44 seems to have resolved the problem.
